### ISSUE TITLE
Use `templatePatch` on ApplicationSets to selectively apply `ignoreDifferences`

### ISSUE THREAD

**Issue by morey-tech** [morey-tech/homelab#21]
Currently the `system` `ApplicationSet` includes `ignoreDifferences` that are specific to `Applications` generated by it. The issue is that they get applied to every `Application` generated by it. This should be fixed using the `templatePatch` resource.
```
  ignoreDifferences:
    - group: apiextensions.k8s.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
      kind: CustomResourceDefinition
    - group: apps
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1config
      kind: Deployment
   ```
